import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Container from "@/components/Container";
const font = Montserrat({ subsets: ["latin"], variable: "--font-mont" });

export const metadata = {
  title: "Ryan's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className} `}>
        <div className="gradient" />
        <div className=" relative min-h-screen w-full bg-light font-mont">
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
